modLoader = "javafml"
loaderVersion = "${forgeVersionRange}"
issueTrackerURL = "https://github.com/${githubUser}/${githubRepo}/issues"
license = "${license}"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
authors = "${modAuthor}"
description = '''${modDescription}'''

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "${forgeVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "${mcVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "ae2"
mandatory = true
versionRange = "${aeVersionRange}"
ordering = "AFTER"
side = "BOTH"
